### ISSUE TITLE
dnsperf.py supply list of openresolvers on comandline instead of file

### ISSUE THREAD

**Issue by stasic** [farrokhi/dnstools#1]
Wouldn't it be nicer if you could supply a list of openresolvers on comandline than having that dnsperf.list file which had to be placed in the same directory as dnsperf.py
Or maybe to put the content of dnsperf.list into dnsperf.py?

**Comment by farrokhi** [comment]
Thank you for the idea. I removed the default `dnsperf.list` file and now use internal list of DNS servers as default. However you can still define your list of DNS servers as a file using `-f` switch.
