### ISSUE TITLE
ImportError: No module named 'dns'

### ISSUE THREAD

**Issue by tehnicadmin** [farrokhi/dnstools#2]
./dnsping.py -s 8.8.8.8 -c 10 wikipedia.org
Traceback (most recent call last):
  File "./dnsping.py", line 34, in <module>
    import dns.rdatatype
ImportError: No module named 'dns'

 ./dnsperf.py wikipedia.orgTraceback (most recent call last):
  File "./dnsperf.py", line 34, in <module>
    import dns.rdatatype
ImportError: No module named 'dns'

**Comment by farrokhi** [comment]
You need to install dnspython library (http://www.dnspython.org/)
