### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by runo280** [farrokhi/dnstools#3]
Got error on this command: `./dnstraceroute.py -s 4.2.2.1 yahoo.com`
**Error**:
`./dnstraceroute.py 4.2.2.1: hostname=yahoo.com rdatatype=A
Traceback (most recent call last):
  File "./dnstraceroute.py", line 193, in <module>
    main()
  File "./dnstraceroute.py", line 126, in main
    icmp_socket = socket.socket(socket.AF_INET, socket.SOCK_RAW, icmp)
  File "/usr/lib/python3.4/socket.py", line 126, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted`

Other commands works well.
OS: Ubuntu 15.10 x64

**Comment by farrokhi** [comment]
How about running ad root?

**Comment by runo280** [comment]
😇 No error

**Comment by farrokhi** [comment]
BTW, you might want to trace to twitter.com and compare the result ;)

-- 
Babak Farrokhi
